# Limited testing using Python 3.9 only, INCLUDING integration tests
# Triggered by a regular (non-draft) pull request created
# Triggered by a regular (non-draft) pull request updated by a new commit
# Triggered by a draft pull request converted into a regular (non-draft) one

name: quick-tests-integration

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:

  quick-tests-integration:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -e .[test]  # coverage reports need -e to capture properly

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 pori_python --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Check with black
      run: |
        pip install black
        black --check -S -l 100 pori_python tests

    - name: Tests with pytest, including integration tests
      run: pytest --junitxml=junit/test-results-3.9.xml --cov ipr --cov-report term --cov-report xml
      env:
        IPR_USER: ${{ secrets.IPR_TEST_USER }}
        IPR_PASS: ${{ secrets.IPR_TEST_PASSWORD }}
        GRAPHKB_USER: ${{ secrets.GKB_TEST_USER }}
        GRAPHKB_PASS: ${{ secrets.GKB_TEST_PASS }}
        EXCLUDE_INTEGRATION_TESTS: 0
