# Limited testing, EXCLUDING integration tests
# Python:
#   - 3.9
# Triggered by:
#   - Pushing a new branch
#   - Addind commit(s) to a branch that is not main or develop, and that is not part of a PR to develop or main branch

name: quick-tests

on:
  push:
    branches-ignore: [main, develop]
  workflow_dispatch:

jobs:

  quick-tests:
    if: ${{ !(
      github.event.pull_request && (
        github.event.pull_request.base.ref == 'main' ||
        github.event.pull_request.base.ref == 'develop'
      )
    ) }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -e .[test]  # coverage reports need -e to capture properly

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 pori_python --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Check with black
      run: |
        pip install black
        black --check -S -l 100 pori_python tests

    - name: Tests with pytest, excluding integration tests
      run: pytest --junitxml=junit/test-results-3.9.xml --cov ipr --cov-report term --cov-report xml
      env:
        IPR_USER: ${{ secrets.IPR_TEST_USER }}
        IPR_PASS: ${{ secrets.IPR_TEST_PASSWORD }}
        GRAPHKB_USER: ${{ secrets.GKB_TEST_USER }}
        GRAPHKB_PASS: ${{ secrets.GKB_TEST_PASS }}
        EXCLUDE_INTEGRATION_TESTS: 1
